# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_module', models.CharField(max_length=255)),
                ('cpu_physical', models.CharField(max_length=255)),
                ('cpu_cores', models.CharField(max_length=255)),
                ('cpu_processor', models.CharField(max_length=255)),
            ],
        ),
    ]
