# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0005_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='cpu\u578b\u53f7')),
                ('frequency', models.CharField(max_length=255, verbose_name='\u9891\u7387')),
                ('physical_cores', models.CharField(max_length=64, verbose_name='\u7269\u7406\u6838\u6570')),
                ('logic_cores', models.CharField(max_length=64, verbose_name='\u903b\u8f91\u6838\u6570')),
                ('hyper_threading', models.BooleanField(verbose_name='\u662f\u5426\u8d85\u7ebf\u7a0b')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_models.Server')),
            ],
            options={
                'verbose_name': 'CPU',
            },
        ),
    ]
