# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0006_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='\u5185\u5b58\u603b\u6570')),
                ('capacity', models.IntegerField(verbose_name='\u5355\u4e2a\u5185\u5b58\u6761\u5927\u5c0f')),
                ('memory_number', models.IntegerField(verbose_name='\u5185\u5b58\u6761\u6570\u91cf')),
                ('frequency', models.IntegerField(verbose_name='\u5185\u5b58\u6761\u9891\u7387')),
                ('slot_total', models.IntegerField(verbose_name='\u5185\u5b58\u69fd\u603b\u6570')),
                ('slot_residue', models.IntegerField(verbose_name='\u5185\u5b58\u69fd\u5269\u4f59\u6570\u91cf')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_models.Server')),
            ],
            options={
                'verbose_name': '\u5185\u5b58',
            },
        ),
    ]
