# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0008_raid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.IntegerField(verbose_name='\u786c\u76d8\u5bb9\u91cf')),
                ('disk_number', models.IntegerField(verbose_name='\u786c\u76d8\u6570\u91cf')),
                ('iface_type', models.CharField(blank=True, max_length=128, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('slot', models.CharField(blank=True, max_length=128, verbose_name='\u63d2\u69fd\u4f4d\u6570\u91cf')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_models.Server')),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
            },
        ),
    ]
