# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0009_disk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='\u7f51\u5361\u578b\u53f7')),
                ('ipaddrs', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('mac', models.CharField(blank=True, max_length=128, verbose_name='\u7f51\u5361mac\u5730\u5740')),
                ('netmask', models.CharField(blank=True, max_length=128, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('gateway', models.CharField(blank=True, max_length=128, verbose_name='\u7f51\u5173')),
                ('dns1', models.CharField(blank=True, max_length=128, verbose_name='DNS1\u5730\u5740')),
                ('dns2', models.CharField(blank=True, max_length=128, verbose_name='DNS2\u5730\u5740')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_models.Server')),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
            },
        ),
    ]
