# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0010_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_models.Asset'),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_models.Asset'),
        ),
    ]
